Feature open ssh port on pubip
epiphany-platform/m-azure-basic-infrastructure pull request #12
Opened 2020-09-25 14:59 UTC by sk4zuzu

2020-09-25 15:45 UTC, mkyc requested changes

2020-09-25 15:45 UTC, mkyc commented on tests/tests.sh
> +  if [[ $nsg_nic_count -ne 2 ]]; then exit 1; fi
can you add ssh connection testing after this line?

2020-09-25 20:15 UTC, sk4zuzu commented on tests/tests.sh
> +  if [[ $nsg_nic_count -ne 2 ]]; then exit 1; fi
Please check in latest commits. :+1:

2020-09-26 11:51 UTC, mkyc approved these changes
LGTM

2020-09-26 11:51 UTC, mkyc commented on resources/terraform/modules/vms/variables.tf
> +  default = "Standard_DS2_v2"
we need to create task that this should be parametrised.

2020-09-26 16:04 UTC, sk4zuzu commented on resources/terraform/modules/vms/variables.tf
> +  default = "Standard_DS2_v2"
:+1: I just added this so we don't repeat the same mistakes.

2020-09-27 15:12 UTC, seriva commented on resources/terraform/modules/vms/variables.tf
> +  default = "Standard_DS2_v2"
Also these should;d be configurable per machine.

2020-09-28 07:56 UTC, mkyc commented on resources/terraform/modules/vms/variables.tf
> +  default = "Standard_DS2_v2"
Yeah, issue #13 is created.

2020-09-28 08:57 UTC, seriva approved these changes

2020-09-28 09:28 UTC, merged