Added devcontainer.
epiphany-platform/m-azure-basic-infrastructure pull request #17
Opened 2020-10-01 07:35 UTC by seriva

Not sure if we want to include this but might be useful for the poor people using Windows.

2020-10-01 13:23 UTC, sk4zuzu submitted a review, later dismissed
LGTM

2020-10-01 13:23 UTC, sk4zuzu commented on .devcontainer/Dockerfile
> +RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
I think we could use just wget or just curl, but not really that important though :thinking:

2020-10-01 13:23 UTC, sk4zuzu commented on .devcontainer/setup-env.sh
> +cd $(pwd)/resources/terraform && terraform init
```suggestion
cd $(pwd)/resources/terraform && terraform init
```

2020-10-02 09:14 UTC, mkyc commented
@atsikham can you have look at this PR if it helps with OS related issues?

2020-10-02 09:41 UTC, atsikham commented
> @atsikham can you have look at this PR if it helps with OS related issues?

I don't think so. Make tasks that we use for modules contain `docker` execution, which is unavailable in devcontainer.

2020-10-02 14:22 UTC, seriva commented
Yeah with WSL2 I also have no issues to build/test/develop it. Only reason I like this approach is that it kind of sets up all your tooling versions and you dont have to build the container every time you need to test.

2020-10-02 14:37 UTC, seriva commented
And one more thing is that it also allows to use some nice plugins for VSCode for various things like bash, python, terraform or whatever the module uses.

2020-10-02 15:30 UTC, sk4zuzu approved these changes
LGTM

2020-10-05 07:21 UTC, rafzei submitted a review, later dismissed
LGTM

2020-10-05 09:08 UTC, atsikham commented
there is an unnecessary space in path - `examples/basic_flow _devcontainer/azure.mk.sample`

2020-10-05 09:09 UTC, atsikham requested changes
Need to remove space from `basic_flow _devcontainer` dir name

2020-10-06 07:46 UTC, seriva commented
@atsikham Fixed the directory issue.

2020-10-06 07:49 UTC, atsikham approved these changes

2020-10-06 07:53 UTC, sk4zuzu approved these changes
LGTM

2020-10-06 07:59 UTC, merged