Rewrite integration tests
epiphany-platform/m-azure-basic-infrastructure pull request #34
Opened 2020-10-20 10:39 UTC by mkyc

2020-10-27 14:39 UTC, atsikham requested changes
Added some comments, but also there is no new changes in changelog. 
Additional general question that probably is not related directly to this PR: is it supposed to extend integration tests? If yes, do you think wheather we should split them to full scope / smoke tests? I'm interested because not in all pipelines it's necessary to execute the full test suite.

Please do not forget disable old UI pipeline.

2020-10-27 14:39 UTC, atsikham commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
Do we need to update licenses with that?

2020-10-27 14:39 UTC, atsikham commented on pipeline.yml
> +      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
Is it supposed to fail job with failed tests? `failTaskOnFailedTests: true`

2020-10-27 14:39 UTC, atsikham commented on integration_test.go
> +}
Could you add some brief documentation (comments) for [godoc](https://blog.golang.org/godoc) tool?

2020-10-27 14:39 UTC, atsikham commented on integration_test.go
> +	imageTag = "epiphanyplatform/azbi:0.0.1"
May be it's better to pass version as a parameter here and pass this value for pipeline or make, just to avoid changing it in the code part during release. WDYT?

2020-10-27 15:15 UTC, mkyc commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
You are right. I added a separate task for this.

2020-10-27 16:28 UTC, mkyc commented on integration_test.go
> +	imageTag = "epiphanyplatform/azbi:0.0.1"
I prefer to make it as clear as possible what gets tested where.

2020-10-27 16:31 UTC, mkyc commented
@atsikham I think you might be right. It is possible that full suite of tests will take hours in case of infrastructure. That might make us divide tests into smaller sets but for now I think it's still ok. 

UI pipeline is already removed.

2020-10-28 10:44 UTC, atsikham commented on integration_test.go
> +	imageTag = "epiphanyplatform/azbi:0.0.1"
If there are a few places to specify the same thing, person who releases module, should do it carefully, or we will have wrong tests after release as a result. With increasing modules count and not automated release process we can have problems with that.

2020-10-28 10:47 UTC, atsikham approved these changes

2020-10-28 10:54 UTC, atsikham commented on integration_test.go
> +	imageTag = "epiphanyplatform/azbi:0.0.1"
@mkyc additional question to clarify - in case of CI, are tests executed for the current changes or for this image that is outdated at time of test job?

2020-10-28 10:55 UTC, atsikham requested changes
Additional comment added.

2020-10-28 11:29 UTC, mkyc commented on integration_test.go
> +	imageTag = "epiphanyplatform/azbi:0.0.1"
@atsikham both comments are very good points. I created separate issues for both of them: #38 and #37 respectively. Thanks!

2020-10-28 11:33 UTC, atsikham approved these changes

2020-10-28 11:37 UTC, erzetpe approved these changes

2020-10-28 11:39 UTC, merged