allow multiple subnets
epiphany-platform/m-azure-basic-infrastructure pull request #47
Opened 2020-12-02 10:55 UTC by mkyc

2020-12-10 12:38 UTC, erzetpe requested changes

2020-12-10 12:38 UTC, erzetpe commented on integration_test.go
> +			wantApplyOutputLastLine: "\tAdd: 7, Change: 0, Destroy: 0",
I am wondering if such tests are not too strict and rigid.

2020-12-10 12:38 UTC, erzetpe commented on integration_test.go
> +			wantApplyOutputLastLine: "\tAdd: 12, Change: 0, Destroy: 0",
Same here.

2020-12-10 12:38 UTC, erzetpe commented on integration_test.go
> +				s := &state.State{}
Oh, it's s.

2020-12-10 12:38 UTC, erzetpe commented on integration_test.go
>  	c := []string{command}
Oh, it's c.

2020-12-10 12:38 UTC, erzetpe commented on integration_test.go
> +	if v, ok := initParams["--vms_rsa"]; ok {
Oh, it's v.

2020-12-10 12:38 UTC, erzetpe commented on cmd/metadata.go
> +		inJson = viper.GetBool("json")
Maybe the better naming will be isJson?

2020-12-10 12:38 UTC, erzetpe commented on cmd/output.go
> +and usage of using your command. For example:
Any description?

2020-12-10 12:38 UTC, erzetpe commented on cmd/plan.go
> +to quickly create a Cobra application.`,
Any description?

2020-12-10 12:38 UTC, erzetpe commented on cmd/root.go
> +to quickly create a Cobra application.`,
Any description?

2020-12-10 12:38 UTC, erzetpe commented on cmd/root.go
> +	// will be global for your application.
Is this default comment needed here?

2020-12-10 12:38 UTC, erzetpe commented on cmd/root.go
> +	}
In the future maybe it will be better also to add some more log levels?

2020-12-10 13:01 UTC, mkyc commented on cmd/apply.go
> +		err := viper.BindPFlags(cmd.Flags())
spf13/viper is integrated with spf13/cobra in that way that it is able to consume command line parameters and environment variables and enrich cobra functionalities that way.

2020-12-10 13:08 UTC, mkyc commented on integration_test.go
> +			wantApplyOutputLastLine: "\tAdd: 7, Change: 0, Destroy: 0",
My opinion is that they are actually quite elastic here since they check only last line. For very specific scenario they are general enough.

2020-12-10 13:08 UTC, mkyc commented on integration_test.go
> +			wantApplyOutputLastLine: "\tAdd: 12, Change: 0, Destroy: 0",
Same as above

2020-12-10 13:13 UTC, mkyc commented on cmd/root.go
> +	}
Yeah, in future :)

2020-12-10 13:17 UTC, mkyc commented on main.go
> +
Checked and with ConsoleWriter having TimeFormat set manually in root.go it's not required any longer.

2020-12-10 13:18 UTC, mkyc commented on cmd/metadata.go
> +		inJson = viper.GetBool("json")
It's for output layout so I renamed it to `useJson`.

2020-12-10 13:43 UTC, seriva reviewed
There is a few places like this:

```			
logger.Info().Msg("Performed following changes: " + msg) 
fmt.Println("Performed following changes: \n\t" + msg)
```

Maybe change the logger to automatically do this? Seems a bit annoying like this.

2020-12-10 13:43 UTC, seriva commented on cmd/apply.go
> +		err := viper.BindPFlags(cmd.Flags())
We don't want to add some actual proper short/long fields?

2020-12-10 13:43 UTC, seriva commented on cmd/destroy.go
> +	Short: "A brief description of your command",
We don't want to add some actual proper short/long fields?

2020-12-10 13:43 UTC, seriva commented on cmd/init.go
> +	Short: "A brief description of your command",
We don't want to add some actual proper short/long fields?

2020-12-10 13:43 UTC, seriva commented on cmd/output.go
> +and usage of using your command. For example:
Jup.

2020-12-10 13:43 UTC, seriva commented on cmd/plan.go
> +to quickly create a Cobra application.`,
Jup.

2020-12-10 13:43 UTC, seriva commented on cmd/root.go
> +to quickly create a Cobra application.`,
Jup.

2020-12-10 13:50 UTC, mkyc commented on cmd/apply.go
> +		err := viper.BindPFlags(cmd.Flags())
It's done in init function: https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/47/files#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR104-R107

It's important to distinguish compile time setup - in that init function - from runtime values harvesting and binding from different places - in here in PreRun.

2020-12-10 13:53 UTC, mkyc commented
From your first comments I just realised that I forgot about documentation part, readme update and examples fixes. I will provide fixes for this today.

2020-12-14 14:27 UTC, erzetpe approved these changes

2020-12-14 14:38 UTC, seriva approved these changes

2020-12-14 14:42 UTC, merged