add azurerm_subnet_network_security_group_association
epiphany-platform/m-azure-basic-infrastructure pull request #69
Opened 2021-02-01 22:52 UTC by ar3ndt

2021-02-02 09:03 UTC, atsikham requested changes
Besides requested changes please check why pipeline fails.

2021-02-02 09:03 UTC, atsikham commented on resources/terraform/networking.tf
> +  count               = length(var.subnets)
Do we need to have such amount of nsg? Can 1 nsg be assigned to multiple subnets?

2021-02-02 10:40 UTC, mkyc commented
Also please notice that tests are failing.

2021-02-02 16:49 UTC, ar3ndt commented on resources/terraform/locals.tf
> +# }
it actually will not be commented once we use only 1 nsg

2021-02-02 16:49 UTC, ar3ndt commented on resources/terraform/networking.tf
> +  count               = length(var.subnets)
yup it can. I am changing this.

2021-02-02 17:56 UTC, ar3ndt commented
> Besides requested changes please check why pipeline fails.

fixed

2021-02-02 19:40 UTC, atsikham approved these changes

2021-02-03 12:53 UTC, mkyc requested changes
When running plan command with `--debug` flag you'll see following warning. It's worth to clear it up: 

...

> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Plan: 11 to add, 0 to change, 0 to destroy.
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > 
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Warning: Interpolation-only expressions are deprecated
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > 
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >   on networking.tf line 37, in resource "azurerm_subnet_network_security_group_association" "subnets_to_nsg":
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >   37:   subnet_id                 = "${azurerm_subnet.subnets[count.index].id}"
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > 
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Terraform 0.11 and earlier required all non-constant expressions to be
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > provided via interpolation syntax, but this pattern is now deprecated. To
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > silence this warning, remove the "${ sequence from the start and the }"
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > sequence from the end of this expression, leaving just the inner expression.
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > 
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Template interpolation syntax is still used to construct strings from
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > expressions when the template includes multiple interpolation sequences or a
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > mixture of literal strings and interpolations. This deprecation applies only
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > to templates that consist entirely of a single interpolation sequence.
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > 
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > (and one more similar warning elsewhere)
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > 
> 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/plan.go:67 > Will perform following changes: Add: 11, Change: 0, Destroy: 0

2021-02-03 18:48 UTC, ar3ndt commented
> When running plan command with `--debug` flag you'll see following warning. It's worth to clear it up:
> 
> ...
> 
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Plan: 11 to add, 0 to change, 0 to destroy.
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Warning: Interpolation-only expressions are deprecated
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >   on networking.tf line 37, in resource "azurerm_subnet_network_security_group_association" "subnets_to_nsg":
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >   37:   subnet_id                 = "${azurerm_subnet.subnets[count.index].id}"
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Terraform 0.11 and earlier required all non-constant expressions to be
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > provided via interpolation syntax, but this pattern is now deprecated. To
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > silence this warning, remove the "${ sequence from the start and the }"
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > sequence from the end of this expression, leaving just the inner expression.
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > Template interpolation syntax is still used to construct strings from
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > expressions when the template includes multiple interpolation sequences or a
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > mixture of literal strings and interpolations. This deprecation applies only
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > to templates that consist entirely of a single interpolation sequence.
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 > (and one more similar warning elsewhere)
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:33 >
> > 2021-02-03T12:49:55Z INF go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/plan.go:67 > Will perform following changes: Add: 11, Change: 0, Destroy: 0

done

2021-02-04 09:25 UTC, atsikham approved these changes

2021-02-04 09:59 UTC, mkyc approved these changes
LGTM

2021-02-04 14:25 UTC, merged