add push image after build/test
epiphany-platform/m-azure-basic-infrastructure pull request #70
Opened 2021-02-02 18:13 UTC by ar3ndt

2021-02-03 12:44 UTC, mkyc requested changes
This logic should be divided into two separate jobs exactly like in here: 

https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/x/mkyc/feature/29-subnet-tests/pipeline.yml

2021-02-03 18:48 UTC, ar3ndt commented
> This logic should be divided into two separate jobs exactly like in here:
> 
> https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/x/mkyc/feature/29-subnet-tests/pipeline.yml

ready

2021-02-04 13:38 UTC, mkyc requested changes
I believe this file should be mirror of already mentioned: https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/x/mkyc/feature/29-subnet-tests/pipeline.yml If there is good reason to improve this file then ok, but I believe we would like to keep them as similar as possible. 

Additional comment is that I believe that it's CI/CD variables (ver or clientId, clientSecret, subscriptionId, and so on ...) should go first, so I'd rather avoid snapping values from Makefile. I believe even [this](https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/x/mkyc/feature/29-subnet-tests/pipeline.yml#L77) should be removed eventually.

2021-02-04 13:38 UTC, mkyc commented on pipeline.yml
> -  ver: dev
this should be used ...

2021-02-04 13:38 UTC, mkyc commented on pipeline.yml
> +            echo "##vso[task.setvariable variable=IMAGE_REPOSITORY]$(make print-IMAGE_REPOSITORY)"
and I don't think you would need to scrap it here from makefile.

2021-02-04 13:38 UTC, mkyc commented on pipeline.yml
> +          VERSION: $(MAJOR_VERSION)
.... and you would use ver variable here.

2021-02-04 13:38 UTC, mkyc commented on pipeline.yml
> +            docker tag $(IMAGE_REPOSITORY):$(MAJOR_VERSION) $(registry_name)/$(IMAGE_REPOSITORY):$(MAJOR_VERSION).$(Build.BuildId)
I don't understand why would we tag image here if it's done automatically in line 80

2021-02-04 13:38 UTC, mkyc commented on pipeline.yml
> +            docker rmi $(registry_name)/$(IMAGE_REPOSITORY):$(Build.BuildId)
add new line

2021-02-04 14:21 UTC, ar3ndt commented on pipeline.yml
> -  ver: dev
why? we use variable set in makefile so no point to have it configured in several places.

2021-02-04 14:21 UTC, ar3ndt commented on pipeline.yml
> +            echo "##vso[task.setvariable variable=IMAGE_REPOSITORY]$(make print-IMAGE_REPOSITORY)"
why not, it is better approach then hardcoding variable.

2021-02-04 14:22 UTC, ar3ndt commented on pipeline.yml
> +          VERSION: $(MAJOR_VERSION)
as above

2021-02-04 14:22 UTC, ar3ndt commented on pipeline.yml
> +            docker tag $(IMAGE_REPOSITORY):$(MAJOR_VERSION) $(registry_name)/$(IMAGE_REPOSITORY):$(MAJOR_VERSION).$(Build.BuildId)
tagging is leftover by previous version, ill remove it

2021-02-04 17:41 UTC, mkyc commented
As I wrote in PR comment: 

> (...) I believe that it's CI/CD variables (ver or clientId, clientSecret, subscriptionId, and so on ...) should go first, so I'd rather avoid scrapping values from Makefile (...)

2021-02-09 09:31 UTC, mkyc submitted a review, later dismissed
LGTM

2021-02-09 10:42 UTC, atsikham approved these changes

2021-02-09 13:33 UTC, mkyc approved these changes

2021-02-09 13:35 UTC, atsikham approved these changes

2021-02-09 13:37 UTC, merged