Fixed reapply the configuration after it has been changed
epiphany-platform/m-azure-basic-infrastructure pull request #87
Opened 2021-05-13 10:58 UTC by atsikham

Task #75 

Changes:
* Removed condition
* Fixed terraform resource dependencies issue:

```text
Error: Invalid count argument
  on modules/vm_group/main.tf line 32, in resource "azurerm_network_interface" "nic":
  32:   count                         = length(local.nic_vm_subnet_association)
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

2021-05-14 11:43 UTC, erzetpe submitted a review, later dismissed

2021-05-24 13:25 UTC, mkyc requested changes

2021-05-24 13:25 UTC, mkyc commented on go.mod
> +	github.com/ahmetb/govvv v0.3.0 // indirect
I don't think you need it added

2021-05-24 13:25 UTC, mkyc commented on go.sum
> +github.com/ahmetb/govvv v0.3.0/go.mod h1:4WRFpdWtc/YtKgPFwa1dr5+9hiRY5uKAL08bOlxOR6s=
and also those

2021-05-25 08:54 UTC, erzetpe approved these changes

2021-05-25 11:13 UTC, mkyc approved these changes

2021-05-25 11:23 UTC, merged