81 resource naming
epiphany-platform/m-azure-basic-infrastructure pull request #91
Opened 2021-06-29 10:39 UTC by mkyc

2021-07-05 13:19 UTC, erzetpe requested changes

2021-07-05 13:19 UTC, erzetpe commented on integration_test.go
> +	rgName := fmt.Sprintf("%s-rg-0", name)
Why have we changed name of the resource group?

2021-07-05 13:19 UTC, erzetpe commented on resources/terraform/main.tf
> +  // follow <prefix>-<resource_type>-<index> naming pattern
Why like this?

2021-07-05 13:38 UTC, mkyc commented on integration_test.go
> +	rgName := fmt.Sprintf("%s-rg-0", name)
because task was to adjust to [this](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/infrastructure/naming-convention.md)

2021-07-05 13:39 UTC, mkyc commented on resources/terraform/main.tf
> +  // follow <prefix>-<resource_type>-<index> naming pattern
because task was to adjust to [this](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/infrastructure/naming-convention.md)

2021-07-06 07:46 UTC, erzetpe approved these changes

2021-07-06 07:47 UTC, erzetpe commented on integration_test.go
> +	rgName := fmt.Sprintf("%s-rg-0", name)
After having conversation we can leave this as it is.

2021-07-06 07:47 UTC, erzetpe commented on resources/terraform/main.tf
> +  // follow <prefix>-<resource_type>-<index> naming pattern
After having conversation we can leave this as it is.

2021-07-06 12:59 UTC, seriva approved these changes

2021-07-06 13:00 UTC, merged