separate azbi from e structures
epiphany-platform/m-azure-basic-infrastructure pull request #97
Opened 2021-10-26 15:12 UTC by mkyc

this PR removes dependencies to e-structures library, moves all related tests into this repository and also refactors some of module mechanisms.

2021-11-05 13:28 UTC, erzetpe requested changes

2021-11-05 13:28 UTC, erzetpe commented on internal/input/input.go
> +func BackupRaw(existingPath, newPath string) error {
Where is this BackupRaw used?

2021-11-05 13:28 UTC, erzetpe commented on internal/input/input.go
> +				}
This code would be better to extract somewhere it doesn't look good.

2021-11-05 15:12 UTC, mkyc commented on internal/terraformer/terraformer.go
> +	terra "github.com/mkyc/go-terraform"
I do not know TBH. Code in there is so ugly that I'm not sure 🙈

2021-11-05 15:14 UTC, mkyc commented on internal/output/output.go
> +		// ok, file does not exist
This code returns errors correctly and comments are just for developers to understand how to correctly handle file existence check.

2021-11-05 15:15 UTC, mkyc commented on internal/input/input.go
> +func BackupRaw(existingPath, newPath string) error {
In `processor` package it each `Pre` function.

2021-11-05 15:18 UTC, mkyc commented on internal/input/input.go
> +				}
What is wrong with it? Its just simple `for`s and only long here is `sl.ReportError()` function which has multiple parameters and that is it.

2021-11-05 15:19 UTC, mkyc commented on internal/to/to.go
> +package to
Good point. Changed.

2021-11-05 15:19 UTC, mkyc commented on internal/utils/test/errors.go
> +
Fixed.

2021-11-08 10:17 UTC, mkyc commented on internal/terraformer/terraformer.go
> +	terra "github.com/mkyc/go-terraform"
I will, but not today :P

2021-11-09 10:08 UTC, erzetpe requested changes

2021-11-09 12:31 UTC, mkyc commented on internal/output/output.go
> +		// ok, file does not exist
Comments in this section fixed.

2021-11-09 14:09 UTC, erzetpe commented on internal/output/output.go
> +		// ok, file does not exist
Good. :)

2021-11-09 14:19 UTC, erzetpe commented on internal/input/input.go
> +				}
I am not a big fan of it. But it can stay as it is.

2021-11-09 14:20 UTC, erzetpe approved these changes

2021-11-09 14:31 UTC, merged